### PR TITLE
Allow lang strings to be translated

### PR DESCRIPTION
**Pull request by ryanmitchell**
This PR moves the lang strings to a translation pack, so they can be translated as required.

### CODE REVIEW

**Review by edalzell — COMMENTED** [review]
Isn't the .json stuff usually done was full strings, like `__("This is the English version")`?

**Comment by ryanmitchell** [comment]
Didn’t know there was a convention? Need them to be keys not strings.

**Comment by edalzell** [comment]
> Didn’t know there was a convention? Need them to be keys not strings.

https://laravel.com/docs/10.x/localization#using-translation-strings-as-keys

**Comment by ryanmitchell** [comment]
Well there you go. I’ll move them to a PHP file then.

**Review by edalzell — APPROVED** [review]

**Pull request merged**
